version: "3.4"
services:
  server:
#    command: bash
    build: .
    image: silentmecha/7dtd:latest
    restart: unless-stopped
    ports:
      - ${TELNETPORT}:8081/tcp
      - ${CONTROLPANELPORT}:8080/tcp
      - ${SERVERPORT}:26900/tcp
      - ${SERVERPORT}:26900/udp
      - ${SERVERPORT_1}:26901/udp
      - ${SERVERPORT_2}:26902/udp
    env_file: .env
    stdin_open: true
    tty: true
    volumes:
      - saved:${STEAM_SAVEDIR}
  sftp:
    image: atmoz/sftp
    restart: unless-stopped
    volumes:
      - saved:/home/${SFT_USER}/saved
    ports:
      - "${SFT_PORT}:22"
    command: ${SFT_USER}:${SFT_PASS}:::saved
volumes:
  saved: