name: Build Image

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Check if latest image exists
        id: check_latest
        run: |
          if docker manifest inspect ${{ github.repository }}:latest >/dev/null 2>&1; then
            echo "LATEST_EXISTS=true" >> $GITHUB_ENV
          else
            echo "LATEST_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Build and push base (if latest does not exist)
        if: env.LATEST_EXISTS == 'false'
        uses: docker/build-push-action@v3
        with:
          push: true
          file: base.Dockerfile
          tags: |
            ${{ github.repository }}:base
            ${{ github.repository }}:latest

      - name: Build and push latest
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ github.repository }}:latest
